### ISSUE TITLE
你好 1.1.5版本哔哩哔哩5.50.0上不能使用

### ISSUE THREAD

**Issue by AkaChou** [meolunr/BiliRoaming#21]
如题，1.1.5版本在哔哩哔哩5.50.0上不能使用

**Comment by lskuoy** [comment]
1.15最高支持应该是5.49，最低应该是5.45.2

**Comment by meolunr** [comment]
不好意思，是服务器挂了。
我在外地出差，要过几天才能回去处理。

**Comment by meolunr** [comment]
Fixed.

**Comment by yujincheng08** [comment]
测试了一下，5.50.0还是不行，5.51同样不行，降级到5.49.0才能用。logcat没有发现`Has replaced play url with proxy server`，但是也没有其他错误信息，错误界面是加载失败。
相关logcat:
```
12-15 09:33:21.639 25117 30177 W System.err: com.bilibili.lib.media.resolver.exception.ResolveMediaSourceException: -9:accept_format not matched with accept_quality, the content is {"code":-10403,"message":"抱歉您所在地区不可观看！"}
12-15 09:33:21.639 25117 30177 W System.err:    at b.gqf.a(BL:82)
12-15 09:33:21.639 25117 30177 W System.err:    at b.gqe.a(BL:173)
12-15 09:33:21.639 25117 30177 W System.err:    at b.gqe.resolveMediaResource(BL:116)
12-15 09:33:21.639 25117 30177 W System.err:    at com.bilibili.lib.media.resolver.resolve.a.a(BL:143)
12-15 09:33:21.640 25117 30177 W System.err:    at com.bilibili.lib.media.resolver.resolve.MediaResolveProvider.a(BL:149)
12-15 09:33:21.640 25117 30177 W System.err:    at com.bilibili.lib.media.resolver.resolve.MediaResolveProvider.call(BL:56)
12-15 09:33:21.640 25117 30177 W System.err:    at android.content.ContentProvider$Transport.call(ContentProvider.java:403)
12-15 09:33:21.640 25117 30177 W System.err:    at android.content.ContentResolver.call(ContentResolver.java:1772)
12-15 09:33:21.640 25117 30177 W System.err:    at com.bilibili.lib.media.resolver.resolve.MediaResolveProvider.a(BL:113)
12-15 09:33:21.640 25117 30177 W System.err:    at com.bilibili.lib.media.resolver.resolve.a.a(BL:93)
12-15 09:33:21.640 25117 30177 W System.err:    at b.gpp.a(BL:36)
12-15 09:33:21.640 25117 30177 W System.err:    at b.gpl.a(BL:32)
12-15 09:33:21.640 25117 30177 W System.err:    at b.gpl.call(BL:18)
12-15 09:33:21.640 25117 30177 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 09:33:21.640 25117 30177 W System.err:    at b.gph$b.call(BL:139)
12-15 09:33:21.640 25117 30177 W System.err:    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 09:33:21.640 25117 30177 W System.err:    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-15 09:33:21.640 25117 30177 W System.err:    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-15 09:33:21.640 25117 30177 W System.err:    at java.lang.Thread.run(Thread.java:764)
```
```
 com.bilibili.lib.media.resolver.exception.ResolveException: empty MediaResource
12-15 09:33:21.642 25117 30177 E BLOG    :      at b.lqr.a(BL:291)
12-15 09:33:21.642 25117 30177 E BLOG    :      at b.lqr.a(BL:230)
12-15 09:33:21.642 25117 30177 E BLOG    :      at b.llr$e.run(BL:71)
12-15 09:33:21.642 25117 30177 E BLOG    :      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
12-15 09:33:21.642 25117 30177 E BLOG    :      at java.util.concurrent.FutureTask.run(FutureTask.java:266)
12-15 09:33:21.642 25117 30177 E BLOG    :      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
12-15 09:33:21.642 25117 30177 E BLOG    :      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
12-15 09:33:21.642 25117 30177 E BLOG    :      at java.lang.Thread.run(Thread.java:764)
```
```
12-15 17:00:12.873  5538  5538 E Xposed  : de.robv.android.xposed.XposedHelpers$ClassNotFoundError: java.lang.ClassNotFoundException: com.bilibili.lib.okhttp.OkHttpURLConnection
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:71)
12-15 17:00:12.873  5538  5538 E Xposed  :      at me.iacn.biliroaming.hooker.BangumiPlayUrlHook.startHook(BangumiPlayUrlHook.java:39)
12-15 17:00:12.873  5538  5538 E Xposed  :      at me.iacn.biliroaming.XposedInit$1.beforeHookedMethod(XposedInit.java:53)
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:341)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.Instrumentation.callApplicationOnCreate(<Xposed>)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5745)
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native Method)
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.ActivityThread.handleBindApplication(<Xposed>)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.ActivityThread.-wrap1(Unknown Source:0)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1657)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.os.Handler.dispatchMessage(Handler.java:106)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.os.Looper.loop(Looper.java:164)
12-15 17:00:12.873  5538  5538 E Xposed  :      at android.app.ActivityThread.main(ActivityThread.java:6499)
12-15 17:00:12.873  5538  5538 E Xposed  :      at java.lang.reflect.Method.invoke(Native Method)
12-15 17:00:12.873  5538  5538 E Xposed  :      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-15 17:00:12.873  5538  5538 E Xposed  :      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:108)
12-15 17:00:12.873  5538  5538 E Xposed  : Caused by: java.lang.ClassNotFoundException: com.bilibili.lib.okhttp.OkHttpURLConnection
12-15 17:00:12.873  5538  5538 E Xposed  :      at java.lang.Class.classForName(Native Method)
12-15 17:00:12.873  5538  5538 E Xposed  :      at java.lang.Class.forName(Class.java:453)
12-15 17:00:12.873  5538  5538 E Xposed  :      at external.org.apache.commons.lang3.ClassUtils.getClass(ClassUtils.java:823)
12-15 17:00:12.873  5538  5538 E Xposed  :      at de.robv.android.xposed.XposedHelpers.findClass(XposedHelpers.java:69)
12-15 17:00:12.873  5538  5538 E Xposed  :      ... 17 more
```
