### ISSUE TITLE
bilibili 5.57.2 番剧解锁功能失效

### ISSUE THREAD

**Issue by rhjdvsgsgks** [meolunr/BiliRoaming#28]
使用的应用转生6.2.3+bilibili5.57.2+bili漫游1.1.8，一开始是可以正常解锁的，这几天突然解锁失败了，具体表现是比较长时间的等待后提示该地区无法播放，log里显示模块是已经正常加载的，显示楼层功能也有效，期间我在日志中发现了这样的报错，不知能否有所帮助
```
04-21 06:57:11.1 : 哔哩哔哩开始加载哔哩漫游模块
04-21 07:04:37.4 : javax.net.ssl.SSLHandshakeException: Connection closed by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
	at okhttp3.internal.connection.c.a(Unknown Source:65)
	at okhttp3.internal.connection.c.a(Unknown Source:24)
	at okhttp3.internal.connection.c.a(Unknown Source:176)
	at okhttp3.internal.connection.f.a(Unknown Source:250)
	at okhttp3.internal.connection.f.a(Unknown Source:0)
	at okhttp3.internal.connection.f.a(Unknown Source:22)
	at okhttp3.internal.connection.a.intercept(Unknown Source:27)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at b.lss.intercept(Unknown Source:138)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at b.lsy.intercept(Unknown Source:176)
	at b.lte.a(Unknown Source:169)
	at b.lth.intercept(Unknown Source:60)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at com.bilibili.lib.okhttp.huc.OkHttpURLConnection$UnexpectedException$1.intercept(Unknown Source:4)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at okhttp3.x.j(Unknown Source:114)
	at okhttp3.x$a.c(Unknown Source:4)
	at b.lsp.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

04-21 07:04:38.0 : javax.net.ssl.SSLHandshakeException: Connection closed by peer
	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
	at okhttp3.internal.connection.c.a(Unknown Source:65)
	at okhttp3.internal.connection.c.a(Unknown Source:24)
	at okhttp3.internal.connection.c.a(Unknown Source:176)
	at okhttp3.internal.connection.f.a(Unknown Source:250)
	at okhttp3.internal.connection.f.a(Unknown Source:0)
	at okhttp3.internal.connection.f.a(Unknown Source:22)
	at okhttp3.internal.connection.a.intercept(Unknown Source:27)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at b.lss.intercept(Unknown Source:138)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at b.lsy.intercept(Unknown Source:176)
	at b.lte.a(Unknown Source:169)
	at b.lth.intercept(Unknown Source:60)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at com.bilibili.lib.okhttp.huc.OkHttpURLConnection$UnexpectedException$1.intercept(Unknown Source:4)
	at b.lte.a(Unknown Source:169)
	at b.lte.a(Unknown Source:6)
	at okhttp3.x.j(Unknown Source:114)
	at okhttp3.x$a.c(Unknown Source:4)
	at b.lsp.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by meolunr** [comment]
感谢反馈
